import { issuesOf, VARIANTS, type Issue, type PageResult, type RunResult } from './results';

interface Group {
  route: string;
  role: string;
  file: string | null;
  url: string;
  placeholder: boolean;
  byVariant: Map<string, PageResult>;
}

interface Finding {
  issue: Issue;
  variants: Set<string>;
}

const PAGE_ROOT = 'packages/web/src/';

function groups(pages: readonly PageResult[]): Group[] {
  const map = new Map<string, Group>();
  for (const p of pages) {
    const key = `${p.route}\u0000${p.role}`;
    let g = map.get(key);
    if (!g) {
      g = {
        route: p.route,
        role: p.role,
        file: p.file,
        url: p.url,
        placeholder: p.placeholder,
        byVariant: new Map(),
      };
      map.set(key, g);
    }
    g.byVariant.set(p.variant, p);
  }
  return [...map.values()];
}

/** Issues of a route+role merged across variants (one line per finding, with where it occurs). */
function findings(g: Group): Finding[] {
  const merged = new Map<string, Finding>();
  for (const [variant, p] of g.byVariant) {
    for (const issue of issuesOf(p)) {
      const key = `${issue.owner}\u0000${issue.key}`;
      const f = merged.get(key);
      if (f) f.variants.add(variant);
      else merged.set(key, { issue, variants: new Set([variant]) });
    }
  }
  const rank = (f: Finding) => (f.issue.severity === 'fail' ? 0 : 1);
  return [...merged.values()].sort((a, b) => rank(a) - rank(b) || a.issue.gate.localeCompare(b.issue.gate));
}

const variantsLabel = (vs: ReadonlySet<string>) =>
  vs.size === VARIANTS.length
    ? 'all variants'
    : VARIANTS.filter((v) => vs.has(v.id))
        .map((v) => v.id)
        .join(', ');

function cell(p: PageResult | undefined): string {
  if (!p) return '–';
  const issues = issuesOf(p);
  const fails = issues.filter((i) => i.severity === 'fail').length;
  const warns = issues.length - fails;
  if (fails) return `**FAIL ${fails}**`;
  return warns ? `pass (${warns} warn)` : 'pass';
}

function keyboardSummary(g: Group): string {
  const parts: string[] = [];
  for (const v of ['1440 light', '360 light']) {
    const k = g.byVariant.get(v)?.keyboard;
    if (!k) continue;
    const w = v.split(' ')[0];
    if (k.primary.kind === 'none') parts.push(`${w}: no control in main`);
    else parts.push(`${w}: ${k.reached ? `${k.tabs} Tab` : 'not reached'}`);
  }
  return parts.join(' · ') || '–';
}

function pageLink(file: string | null): string {
  return file ? `\`${file.replace(/^pages\//, '')}\`` : '–';
}

export function renderReport(run: RunResult): string {
  const gs = groups(run.pages);
  const all = gs.flatMap((g) => findings(g).map((f) => ({ g, f })));
  const failing = all.filter(({ f }) => f.issue.severity === 'fail');
  const shared = all.filter(({ f }) => f.issue.owner !== 'page');
  const pageVisits = run.pages.length;
  const failedVisits = run.pages.filter((p) => issuesOf(p).some((i) => i.severity === 'fail')).length;
  const routingFails = run.routing.filter((r) => !r.ok);

  const lines: string[] = [];
  lines.push('# Accessibility and UI quality report');
  lines.push('');
  lines.push(
    `Generated by \`pnpm --filter @aoc/web a11y\` (packages/web/test/a11y/check.ts) on ${run.finishedAt} — ` +
      `commit \`${run.commit}\` (${run.branch}), axe-core ${run.axeVersion}, ${run.browser}.`,
  );
  lines.push(
    `Demo data seeded into \`${run.dataDir}\`; aocd on claude-sim. Each route is visited per role at 1440×900 and 360×740, light and dark.`,
  );
  lines.push('');
  lines.push('## Verdict');
  lines.push('');
  lines.push(
    `**${failedVisits ? 'FAIL' : 'PASS'}** — ${failedVisits} of ${pageVisits} page visits fail a gate; ` +
      `${new Set(failing.map(({ g }) => `${g.route} ${g.role}`)).size} of ${gs.length} route/role pairs have failing findings; ` +
      `role routing ${routingFails.length ? `**${routingFails.length} wrong**` : 'correct'}.`,
  );
  lines.push('');
  lines.push('Gates (FAIL unless noted):');
  lines.push('');
  lines.push(
    '- **axe** — axe-core rules tagged wcag2a/aa, wcag21a/aa, wcag22aa and best-practice; serious and critical fail, moderate and minor warn.',
  );
  lines.push('- **scroll** — no horizontal page scroll at 360 px.');
  lines.push(
    '- **motion** — no infinite CSS or SMIL animation (§12: a mark moves only when an event moved it); anything still running at rest warns.',
  );
  lines.push(
    '- **charts** — every chart-sized SVG prints its numbers as visible text (beside it or as SVG text, for phones) and gives them to screen readers (a `role="img"` name that states them, or the printed text beside it); an exposed svg needs `role="img"` and a name, or `aria-hidden`. Data colours under 3:1 against the surface behind the chart warn.',
  );
  lines.push(
    "- **keyboard** — from page load, Tab reaches the primary action (first `[data-primary-action]`, else `.aoc-btn--primary` in main, else main's first control); the whole tab order is walked and every stop must show a focus indicator; following the skip link puts focus in main.",
  );
  lines.push(
    '- **console / requests** — no console errors or uncaught exceptions, no failed or ≥ 400 requests (except the 404 of a deliberately missing id, and the anonymous `/api/auth/me` probe).',
  );
  lines.push('');

  lines.push('## Pages');
  lines.push('');
  lines.push(
    `| Route | Role | Page file (src/pages/) | ${VARIANTS.map((v) => v.id).join(' | ')} | Tab stops to primary |`,
  );
  lines.push(`| --- | --- | --- | ${VARIANTS.map(() => '---').join(' | ')} | --- |`);
  for (const g of gs) {
    const route = g.placeholder ? `${g.route} (no seeded id)` : g.route;
    lines.push(
      `| \`${route}\` | ${g.role} | ${pageLink(g.file)} | ${VARIANTS.map((v) => cell(g.byVariant.get(v.id))).join(' | ')} | ${keyboardSummary(g)} |`,
    );
  }
  lines.push('');

  if (run.routing.length) {
    lines.push('## Role routing');
    lines.push('');
    lines.push('| Role | Opens | Expected | Landed | Result |');
    lines.push('| --- | --- | --- | --- | --- |');
    for (const r of run.routing)
      lines.push(
        `| ${r.role} | \`${r.path}\` | \`${r.expected}\` | \`${r.actual}\` | ${r.ok ? 'pass' : '**FAIL**'} |`,
      );
    lines.push('');
  }

  lines.push('## Shared-layer findings');
  lines.push('');
  lines.push(
    'Nodes outside `<main>` (shell: top bar, nav, skip link, portal header) or rendered by a shared component (`aoc-*` block from src/components, src/charts).',
  );
  lines.push('');
  const byOwner = new Map<string, Map<string, { f: Finding; routes: Set<string>; variants: Set<string> }>>();
  for (const { g, f } of shared) {
    const owner = byOwner.get(f.issue.owner) ?? new Map();
    byOwner.set(f.issue.owner, owner);
    const e = owner.get(f.issue.key) ?? { f, routes: new Set<string>(), variants: new Set<string>() };
    e.routes.add(`${g.route} (${g.role})`);
    for (const v of f.variants) e.variants.add(v);
    owner.set(f.issue.key, e);
  }
  if (byOwner.size === 0) lines.push('None.');
  for (const [owner, entries] of [...byOwner].sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(`### ${owner === 'shell' ? 'Shell (outside main)' : `\`${owner}\``}`);
    lines.push('');
    for (const { f, routes, variants } of entries.values()) {
      const where = routes.size > 4 ? `${routes.size} route/role pairs` : [...routes].join(', ');
      lines.push(
        `- ${f.issue.severity === 'fail' ? '**FAIL**' : 'warn'} [${f.issue.gate}] ${f.issue.text} — on ${where} (${variantsLabel(variants)})`,
      );
    }
    lines.push('');
  }

  lines.push('## Page findings (for page owners)');
  lines.push('');
  let any = false;
  for (const g of gs) {
    const fs = findings(g).filter((f) => f.issue.owner === 'page');
    if (!fs.length) continue;
    any = true;
    const file = g.file ? ` — ${PAGE_ROOT}${g.file}` : '';
    lines.push(`### \`${g.route}\` as ${g.role}${file}`);
    lines.push('');
    if (g.placeholder)
      lines.push(
        `Visited as \`${g.url}\`: the demo seed has no such record, so this is the not-found state.`,
      );
    for (const f of fs)
      lines.push(
        `- ${f.issue.severity === 'fail' ? '**FAIL**' : 'warn'} [${f.issue.gate}] ${f.issue.text} (${variantsLabel(f.variants)})`,
      );
    lines.push('');
  }
  if (!any) lines.push('None.');
  if (run.notes.length) {
    lines.push('');
    lines.push('## Notes');
    lines.push('');
    for (const n of run.notes) lines.push(`- ${n}`);
  }
  lines.push('');
  return lines.join('\n');
}
